[workspace]

members = [
    "algebra",
    "bench-utils",
    "primitives",
    "proof-systems",
    "r1cs/core",
    "r1cs/gadgets/std",
    "r1cs/gadgets/crypto",
]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = true
debug = true

# Uncomment these lines for local development paths
#
#[patch.'https://github.com/HorizenOfficial/ginger-lib']
#algebra = { path = './algebra' }
#r1cs-core = { path = "./r1cs/core" }
#
#[patch.'https://github.com/HorizenLabs/marlin']
#marlin = { path = '../marlin' }
#
#[patch.'https://github.com/HorizenLabs/poly-commit']
#poly-commit = { path = '../poly-commit' }
